name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    env:
      CI: ""
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Create the .env file with the secrets
      - name: Create .env file
        run: |
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" >> .env
          echo "REACT_APP_JWT_BASE_URL=${{ secrets.REACT_APP_JWT_BASE_URL }}" >> .env
          echo "REACT_APP_MONGODB_DATA_SOURCE=${{ secrets.REACT_APP_MONGODB_DATA_SOURCE }}" >> .env
          echo "REACT_APP_MONGODB_DATABASE=${{ secrets.REACT_APP_MONGODB_DATABASE }}" >> .env

      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAW_BRAINER_RULES_EDITOR }}
          channelId: live
          projectId: law-brainer-rules-editor
